name: Deceiv
version: '${version}'
main: com.japicraft.Deceiv
bootstrapper: com.japicraft.Bootstrapper
description: A modern murder mystery minigame.
api-version: '26.2'
authors: [ japicraft ]
website: https://japicraft.com
folia-supported: false
dependencies:
  server:
    BetterModel:
      load: BEFORE
      required: false
