name: Deceiv
on:
  workflow_dispatch:
    inputs:
      project_version:
        description: 'Current version of the project: (e.g., 26.1.0)'
        required: true
      minecraft_version:
        description: 'Lowest supported Minecraft version: (e.g., 26.1.2)'
        required: true
run-name: Deceiv Build Version ${{ inputs.project_version }}
jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: check version
        run: |
          if git rev-parse --verify "refs/tags/${{ inputs.pack_version }}" >/dev/null 2>&1; then
            echo "Version ${{ inputs.pack_version }} already exists!"
            exit 1
          fi
      - name: replace version and hash
        run: |
          sed -i "s/INDEV/${{ inputs.pack_version }}/g" build.gradle.kts
          echo "Replaced PACK_VERSION with '${{ inputs.pack_version }}' successfully!"
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v6
      - run: gradle shadowJar
      - uses: Kir-Antipov/mc-publish@v3
        with:
          name: Deceiv Plugin for Minecraft ${{ inputs.minecraft_version }}+
          version: ${{ inputs.project_version }}
          files: 'build/libs/deceiv.jar'
          loaders: paper
          game-versions: ">=${{ inputs.minecraft_version }}"
          modrinth-id: AnCT3bvm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: check version
        run: |
          if git rev-parse --verify "refs/tags/${{ inputs.pack_version }}" >/dev/null 2>&1; then
            echo "Version ${{ inputs.pack_version }} already exists!"
            exit 1
          fi
      - name: replace version and hash
        run: |
          sed -i "s/PACK_VERSION/${{ inputs.pack_version }}/g" pack.mcmeta
          echo "Replaced PACK_VERSION with '${{ inputs.pack_version }}' successfully!"
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          sed -i "s/GIT_HASH/$calculatedSha/g" pack.mcmeta
          echo "Replaced GIT_HASH with '$calculatedSha' successfully!"
      - uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: options.toml
      - uses: Kir-Antipov/mc-publish@v3
        with:
          name: Deceiv Pack for Minecraft ${{ inputs.minecraft_version }}+
          version: ${{ inputs.project_version }}
          files: 'deceiv.zip'
          loaders: minecraft
          game-versions: ">=${{ inputs.minecraft_version }}"
          modrinth-id: AnCT3bvm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
